import { describe, it, expect } from "vitest";
import {
  fitScoreAtMinute,
  fitScoreForChunk,
  organiserFit,
  inviteeCoverage,
  scoreSlot,
  rankCandidates,
  fitCurveFromContextConfig,
  type FitCurve,
  type InviteeResponse,
} from "../../src/polls/scoring";

// Parity fixtures below were generated by running the actual Python
// evaluator (solver/src/solver/fit_curve.py) once, not hand-derived:
//
//   cd solver && uv run python3 -c "
//   from datetime import time
//   from solver.fit_curve import FitCurveEvaluator
//   from solver.schema import FitCurve
//   ...
//   "
//
// See the T3 report for the exact commands and their full output.

// Curve A mirrors solver/tests/test_fit_curve.py's deep_curve fixture.
const CURVE_A: FitCurve = { peak_start: "09:00", peak_end: "12:00", falloff_end: "16:00" };
// peak_start = 00:00 edge case.
const CURVE_B: FitCurve = { peak_start: "00:00", peak_end: "08:00", falloff_end: "20:00" };
// falloff_end === peak_end (zero-length ramp after peak).
const CURVE_C: FitCurve = { peak_start: "09:00", peak_end: "17:00", falloff_end: "17:00" };
// span = 200 minutes, chosen so several minutes land exactly on a .5
// round-half-to-even boundary (Python round(), not JS Math.round()).
const CURVE_D: FitCurve = { peak_start: "09:00", peak_end: "12:00", falloff_end: "15:20" };

describe("fitScoreAtMinute — Python parity", () => {
  it("curve A: zero inside peak, ramps either side, saturates past falloff", () => {
    expect(fitScoreAtMinute(CURVE_A, 0)).toBe(100);
    expect(fitScoreAtMinute(CURVE_A, 270)).toBe(50);
    expect(fitScoreAtMinute(CURVE_A, 540)).toBe(0);
    expect(fitScoreAtMinute(CURVE_A, 600)).toBe(0);
    expect(fitScoreAtMinute(CURVE_A, 720)).toBe(0);
    expect(fitScoreAtMinute(CURVE_A, 840)).toBe(50);
    expect(fitScoreAtMinute(CURVE_A, 959)).toBe(100);
    // minute past falloff_end (960): saturates at MAX_SCORE.
    expect(fitScoreAtMinute(CURVE_A, 960)).toBe(100);
    expect(fitScoreAtMinute(CURVE_A, 1020)).toBe(100);
    expect(fitScoreAtMinute(CURVE_A, 1259)).toBe(100);
  });

  it("curve B: peak_start = 00:00 skips the before-peak ramp entirely", () => {
    expect(fitScoreAtMinute(CURVE_B, 0)).toBe(0);
    expect(fitScoreAtMinute(CURVE_B, 480)).toBe(0);
    expect(fitScoreAtMinute(CURVE_B, 840)).toBe(50);
    expect(fitScoreAtMinute(CURVE_B, 1260)).toBe(100);
  });

  it("curve C: falloff_end === peak_end jumps straight to MAX_SCORE past the peak", () => {
    expect(fitScoreAtMinute(CURVE_C, 1020)).toBe(0);
    expect(fitScoreAtMinute(CURVE_C, 1021)).toBe(100);
    expect(fitScoreAtMinute(CURVE_C, 1080)).toBe(100);
  });

  it("curve D: exact .5 ties round half-to-even like Python's round(), not JS Math.round", () => {
    // 745 -> ratio*100 = 12.5 exactly; Python round(12.5) == 12 (12 is even).
    expect(fitScoreAtMinute(CURVE_D, 745)).toBe(12);
    // 795 -> ratio*100 = 37.5 exactly; Python round(37.5) == 38 (38 is even).
    expect(fitScoreAtMinute(CURVE_D, 795)).toBe(38);
  });
});

describe("fitScoreForChunk — Python parity", () => {
  it("sums per-15-min-slot scores across the chunk", () => {
    expect(fitScoreForChunk(CURVE_A, 660, 90)).toBe(6);
    expect(fitScoreForChunk(CURVE_A, 0, 60)).toBe(383);
    // Exercises the same round-half-to-even boundaries as the curve D unit test.
    expect(fitScoreForChunk(CURVE_D, 720, 90)).toBe(113);
  });
});

describe("organiserFit", () => {
  it("normalises to [0,1], higher is better, using organiser-timezone minute-of-day", () => {
    // 2026-08-03T00:00:00Z == Mon 10:00 Australia/Sydney (AEST, +10) == minute 600.
    const fit = organiserFit(CURVE_A, "2026-08-03T00:00:00.000Z", 15, "Australia/Sydney");
    // fitScoreAtMinute(CURVE_A, 600) == 0 (inside peak) -> fit == (100 - 0) / 100 == 1.
    expect(fit).toBeCloseTo(1, 10);
  });

  it("1.0 is fully in-peak, 0.0 is fully saturated-worst, for a single 15-min slot", () => {
    // minute 720 (12:00, peak boundary) -> score 0 -> fit 1.
    const best = organiserFit(CURVE_A, "2026-08-03T02:00:00.000Z", 15, "Australia/Sydney");
    expect(best).toBeCloseTo(1, 10);
    // minute 960 (16:00, at falloff_end) -> score 100 -> fit 0.
    const worst = organiserFit(CURVE_A, "2026-08-03T06:00:00.000Z", 15, "Australia/Sydney");
    expect(worst).toBeCloseTo(0, 10);
  });

  it("computes minute-of-day from Intl in the given zone across a Sydney DST spring-forward, never manual offset arithmetic", () => {
    // 2026-10-04 02:00 Australia/Sydney does not exist: clocks jump 02:00 -> 03:00 AEDT.
    // Verified independently via Python zoneinfo:
    //   2026-10-03T15:00:00Z -> 2026-10-04T01:00:00+10:00 (AEST, minute 60)
    //   2026-10-03T16:00:00Z -> 2026-10-04T03:00:00+11:00 (AEDT, minute 180 — 02:00 is skipped)
    //   2026-10-03T17:00:00Z -> 2026-10-04T04:00:00+11:00 (AEDT, minute 240)
    // A fixed-offset (manual arithmetic) implementation would compute 16:00Z
    // as local 02:00 (minute 120), which does not exist, or silently drift by
    // an hour on either side of the transition. Expected fit-curve scores
    // at those minutes-of-day (Python parity, curve A, n=1 slot of 15 min):
    //   minute 60  -> score 89 -> fit (100-89)/100 = 0.11
    //   minute 180 -> score 67 -> fit (100-67)/100 = 0.33
    //   minute 240 -> score 56 -> fit (100-56)/100 = 0.44
    const before = organiserFit(CURVE_A, "2026-10-03T15:00:00.000Z", 15, "Australia/Sydney");
    const atTransition = organiserFit(CURVE_A, "2026-10-03T16:00:00.000Z", 15, "Australia/Sydney");
    const after = organiserFit(CURVE_A, "2026-10-03T17:00:00.000Z", 15, "Australia/Sydney");
    expect(before).toBeCloseTo(0.11, 10);
    expect(atTransition).toBeCloseTo(0.33, 10);
    expect(after).toBeCloseTo(0.44, 10);
  });
});

describe("inviteeCoverage", () => {
  it("covered ('free') iff every 30-min cell of [s, s+d) is painted free", () => {
    const cells = new Map([
      ["2026-08-03T00:00:00.000Z", "free" as const],
      ["2026-08-03T00:30:00.000Z", "free" as const],
    ]);
    expect(inviteeCoverage(cells, "2026-08-03T00:00:00.000Z", 60)).toBe("free");
  });

  it("'none' when any covering cell is unpainted", () => {
    const cells = new Map([["2026-08-03T00:00:00.000Z", "free" as const]]);
    expect(inviteeCoverage(cells, "2026-08-03T00:00:00.000Z", 60)).toBe("none");
  });

  it("'if_needed' when any covering cell is if_needed, even if others are free", () => {
    const cells = new Map([
      ["2026-08-03T00:00:00.000Z", "free" as const],
      ["2026-08-03T00:30:00.000Z", "if_needed" as const],
    ]);
    expect(inviteeCoverage(cells, "2026-08-03T00:00:00.000Z", 60)).toBe("if_needed");
  });

  it("a 45-min slot spans a partial third cell — that cell must still be painted", () => {
    // Slot 00:00-00:45 overlaps cells [00:00,00:30) and [00:30,01:00) (tail overlap only).
    const covered = new Map([
      ["2026-08-03T00:00:00.000Z", "free" as const],
      ["2026-08-03T00:30:00.000Z", "free" as const],
    ]);
    expect(inviteeCoverage(covered, "2026-08-03T00:00:00.000Z", 45)).toBe("free");

    const missingTail = new Map([["2026-08-03T00:00:00.000Z", "free" as const]]);
    expect(inviteeCoverage(missingTail, "2026-08-03T00:00:00.000Z", 45)).toBe("none");
  });

  it("a slot not aligned to a cell boundary still requires its overlapping cells", () => {
    // Slot starts 00:15 for 30 min -> overlaps cells [00:00,00:30) and [00:30,01:00).
    const cells = new Map([
      ["2026-08-03T00:00:00.000Z", "free" as const],
      ["2026-08-03T00:30:00.000Z", "free" as const],
    ]);
    expect(inviteeCoverage(cells, "2026-08-03T00:15:00.000Z", 30)).toBe("free");
  });
});

describe("scoreSlot", () => {
  const freeCells = (starts: string[]) => new Map(starts.map((s) => [s, "free" as const]));

  it("multiplies organiser fit by every required invitee's weight", () => {
    const responses: InviteeResponse[] = [
      { inviteeId: "a", cells: freeCells(["2026-08-03T02:00:00.000Z"]) },
      {
        inviteeId: "b",
        cells: new Map([["2026-08-03T02:00:00.000Z", "if_needed" as const]]),
      },
    ];
    // Slot at minute 720 (12:00) is fully in-peak -> organiserFit == 1.
    const result = scoreSlot(
      CURVE_A,
      "2026-08-03T02:00:00.000Z",
      15,
      "Australia/Sydney",
      responses,
      ["a", "b"],
    );
    expect(result).not.toBeNull();
    expect(result!.organiserFit).toBeCloseTo(1, 10);
    expect(result!.weights).toEqual(
      expect.arrayContaining([
        { inviteeId: "a", weight: 1.0 },
        { inviteeId: "b", weight: 0.5 },
      ]),
    );
    // score = organiserFit(1) * 1.0 * 0.5
    expect(result!.score).toBeCloseTo(0.5, 10);
  });

  it("returns null when any required invitee has no coverage", () => {
    const responses: InviteeResponse[] = [
      { inviteeId: "a", cells: freeCells(["2026-08-03T02:00:00.000Z"]) },
    ];
    const result = scoreSlot(
      CURVE_A,
      "2026-08-03T02:00:00.000Z",
      15,
      "Australia/Sydney",
      responses,
      ["a", "b"], // "b" never responded
    );
    expect(result).toBeNull();
  });
});

describe("rankCandidates", () => {
  it("sorts best-first by score, ties broken by earliest start", () => {
    // Two candidates, both fully-covered by both invitees at weight 1.0, so
    // ranking is purely by organiser fit: minute 720 (in-peak, fit=1) beats
    // minute 960 (at falloff_end, fit=0).
    const best = "2026-08-03T02:00:00.000Z"; // 12:00 Sydney
    const worst = "2026-08-03T06:00:00.000Z"; // 16:00 Sydney
    const responses: InviteeResponse[] = [
      { inviteeId: "a", cells: freeAt([best, worst]) },
      { inviteeId: "b", cells: freeAt([best, worst]) },
    ];
    const ranked = rankCandidates(
      [worst, best],
      responses,
      ["a", "b"],
      CURVE_A,
      15,
      "Australia/Sydney",
    );
    expect(ranked.map((r) => r.slotStartUtc)).toEqual([best, worst]);
  });

  it("breaks exact ties by earliest start", () => {
    // Both candidates land at minute 720 (in-peak) on different days -> identical fit.
    const first = "2026-08-03T02:00:00.000Z";
    const second = "2026-08-04T02:00:00.000Z";
    const responses: InviteeResponse[] = [
      { inviteeId: "a", cells: freeAt([first, second]) },
    ];
    const ranked = rankCandidates(
      [second, first],
      responses,
      ["a"],
      CURVE_A,
      15,
      "Australia/Sydney",
    );
    expect(ranked[0]!.slotStartUtc).toBe(first);
    expect(ranked[1]!.slotStartUtc).toBe(second);
  });

  it("excludes candidates where the required set is not fully covered", () => {
    const covered = "2026-08-03T02:00:00.000Z";
    const uncovered = "2026-08-03T06:00:00.000Z";
    const responses: InviteeResponse[] = [{ inviteeId: "a", cells: freeAt([covered]) }];
    const ranked = rankCandidates(
      [covered, uncovered],
      responses,
      ["a"],
      CURVE_A,
      15,
      "Australia/Sydney",
    );
    expect(ranked.map((r) => r.slotStartUtc)).toEqual([covered]);
  });
});

function freeAt(starts: string[]): Map<string, "free" | "if_needed"> {
  return new Map(starts.map((s) => [s, "free" as const]));
}

describe("fitCurveFromContextConfig", () => {
  // The REAL, currently-live config_contexts row for ('__default__', 'meeting'),
  // verbatim — verified empirically by applying every migration through
  // worker/migrations/0031_booking_location.sql in the vitest D1 test harness
  // and querying `SELECT body FROM config_contexts WHERE context = 'meeting'`.
  // worker/migrations/0005_fix_config_contexts.sql collapses the 0002 seed's
  // descriptive {peak_windows, allowed_start, allowed_end} shape to this
  // single-window triple (ON CONFLICT DO UPDATE) because "the solver schema
  // ... only accepts the {peak_start, peak_end, falloff_end} triple"; 0007
  // explicitly leaves 'meeting' as 0005 set it; 0017's owner_subject re-key
  // carries the body over verbatim. So this — not the 0002 literal — is what
  // every real caller (dev, prod, and this test env) actually reads.
  const LIVE_MEETING_ROW_JSON =
    '{"context":"meeting","fit_curve":{"peak_start":"10:00","peak_end":"11:00","falloff_end":"17:00"},' +
    '"max_minutes_per_day":180,"max_contiguous_minutes":120,' +
    '"over_daily_cap_penalty_per_15min":25,"over_streak_cap_penalty_per_15min":25}';

  it("parses the real seeded __default__ 'meeting' row (post-migration shape)", () => {
    const raw = JSON.parse(LIVE_MEETING_ROW_JSON);
    expect(fitCurveFromContextConfig(raw)).toEqual<FitCurve>({
      peak_start: "10:00",
      peak_end: "11:00",
      falloff_end: "17:00",
    });
  });

  it("returns null for the historical 0002-seed multi-window shape (peak_windows/allowed_*)", () => {
    // worker/migrations/0002_seed_config.sql's original literal — no longer
    // reachable in practice (0005 overwrites it before any code runs), but
    // the evaluator has no lossless single-window representation for it, so
    // this must degrade to null rather than guess.
    const raw = JSON.parse(
      '{"context":"meeting","fit_curve":{"peak_windows":[{"start":"10:00","end":"11:00"},' +
        '{"start":"14:00","end":"15:00"}],"allowed_start":"09:00","allowed_end":"17:00"},' +
        '"max_minutes_per_day":180,"max_contiguous_minutes":120,' +
        '"over_daily_cap_penalty_per_15min":25,"over_streak_cap_penalty_per_15min":25}',
    );
    expect(fitCurveFromContextConfig(raw)).toBeNull();
  });

  it("returns null for missing fit_curve, non-object input, and non-string/malformed fields", () => {
    expect(fitCurveFromContextConfig({ context: "meeting" })).toBeNull();
    expect(fitCurveFromContextConfig(null)).toBeNull();
    expect(fitCurveFromContextConfig(undefined)).toBeNull();
    expect(fitCurveFromContextConfig("not an object")).toBeNull();
    expect(fitCurveFromContextConfig(42)).toBeNull();
    expect(fitCurveFromContextConfig([])).toBeNull();
    expect(
      fitCurveFromContextConfig({ fit_curve: { peak_start: "10:00", peak_end: "11:00" } }),
    ).toBeNull(); // falloff_end missing
    expect(
      fitCurveFromContextConfig({
        fit_curve: { peak_start: 600, peak_end: "11:00", falloff_end: "17:00" },
      }),
    ).toBeNull(); // peak_start not a string
    expect(
      fitCurveFromContextConfig({
        fit_curve: { peak_start: "9am", peak_end: "11:00", falloff_end: "17:00" },
      }),
    ).toBeNull(); // not HH:MM
  });

  it("parses the other real seeded contexts too (deep/admin/physical/family, post-0007)", () => {
    // worker/migrations/0007_update_fit_curves.sql's live shapes for contexts
    // that DO use the plain triple already — sanity-checks the adapter isn't
    // meeting-specific.
    expect(
      fitCurveFromContextConfig(
        JSON.parse(
          '{"context":"deep","fit_curve":{"peak_start":"12:00","peak_end":"16:00","falloff_end":"17:00"}}',
        ),
      ),
    ).toEqual<FitCurve>({ peak_start: "12:00", peak_end: "16:00", falloff_end: "17:00" });
  });
});
